import { chromium } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { waitForSignInCode } from './src/u1-capital-cycle/otp.support.ts';
const env = Object.fromEntries(readFileSync('../../.env.local','utf8').split('\n').filter(l=>l.includes('=')&&!l.startsWith('#')).map(l=>{const i=l.indexOf('=');return [l.slice(0,i).trim(), l.slice(i+1).trim().replace(/^"|"$/g,'')];}));
const email = process.argv[2] === 'investor' ? (env.E2E_FUND_EMAIL ?? (env.E2E_DIRECTOR_EMAIL ?? env.PRIVY_BUSINESS_DIRECTOR_EMAILS.split(',')[0].trim()).replace(/^[^@]+/, 'inv-woodgrove')) : (env.E2E_DIRECTOR_EMAIL ?? env.PRIVY_BUSINESS_DIRECTOR_EMAILS.split(',')[0].trim());
const b = await chromium.connectOverCDP('http://127.0.0.1:9222');
const page = b.contexts()[0].pages()[0];
const box = page.getByPlaceholder(/email/i).or(page.getByRole('textbox').first());
await box.fill(email);
const sentAt = Date.now();
await page.getByRole('button', { name: /submit|continue|next/i }).first().click();
console.log('code sent to', email);
const code = await waitForSignInCode(email, sentAt, env.RESEND_API_KEY);
await page.getByRole('textbox').first().click();
await page.keyboard.type(code, { delay: 80 });
await page.getByRole('heading', { level: 1 }).waitFor({ timeout: 60000 });
await page.waitForTimeout(1500);
await page.screenshot({ path: '/tmp/claude-1000/-home-orbbit-receivables-flow/demo/now.png' });
console.log('signed in →', page.url());
await b.close();
